### ISSUE TITLE
Submit to F-droid main repo

### ISSUE THREAD

**Issue by adeekshith** [adeekshith/watomatic#132]
- [x] Add Fastlane metadata (refer [Izzy's Fastlane Cheat Sheet](https://gitlab.com/snippets/1895688)) ([src](https://github.com/adeekshith/watomatic/pull/81#issue-575967818))
    - Example, see initial meta data added by Izzy: #81
    - Include screenshots (Izzy recommends screenshots without frames)
- [x] Make a release (tagged) after above step as Fastlane must be available at the latest tag. ([src](https://github.com/adeekshith/watomatic/issues/65#issuecomment-781621611))
- [x] Raise an F-Droid RFP: https://gitlab.com/fdroid/rfp/issues

**Comment by adeekshith** [comment]
@IzzySoft Raised RFP for F-Droid 😃

Left the summary and description section as-is as we already have fastlane data. Please let me know in case I did anything wrong. Thank you!

https://gitlab.com/fdroid/rfp/-/issues/1660

**Comment by IzzySoft** [comment]
Thanks! Saw it, and it's already being worked on \o/
