### ISSUE TITLE
Deploy on F-Droid?

### ISSUE THREAD

**Issue by aschrijver** [adeekshith/watomatic#138]
Wonderful app! Just what's needed, thanks.

This was the first time I saw IzzyOnDroid appstore. Would love to see this on F-Droid, which is what I primarily use.

**Comment by adeekshith** [comment]
Hi @aschrijver 
Glad to see some F-Droid ❤️ 
Submitting to F-droid main repo is being worked on 😃🙌. See issue https://github.com/adeekshith/watomatic/issues/132
I already did the submission yesterday and F-Droid team is working on packaging it.

About IzzyOnDroid: [IzzySoft](https://github.com/IzzySoft) maintains IzzyOnDroid and he is also a maintainer at F-Droid. He is the one helping us packing to F-Droid (thank him here #132 )
IzzyOnDroid includes projects are that not yet processed by F-Droid main repo and also has a slightly relaxed criteria of inclusion (but verified and malware scanned) so you might find some interesting apps over there which will never make it to main F-Droid repo.

Thanks,
Deekshith
Support us by [**being a patron (liberapay)**](https://liberapay.com/dk/donate) or [**buy me ☕️ (paypal)**](https://paypal.me/deek). Even a few cent symbolic contribution counts.
