### ISSUE TITLE
Need to run at startup as Auto reply not working when device Restarted

### ISSUE THREAD

**Issue by adeekshith** [adeekshith/watomatic#143]
A few users complained that this app does not run after restarting the phone.

- We might need either or all of these permissions: run at startup, prevent phone from sleeping

Thats my preliminary thought but need to verify whats the better way.

**Comment by aschrijver** [comment]
Being an exemplar of trustworthiness is important given the USP of the app is also related to that. You might think about having an opt-in for more pervasive permissions, and at least describe what each of your permissions are used / why they are required.

**Comment by adeekshith** [comment]
Of course! I am very cautious of adding new permissions. In fact, the current version has zero default permissions. Well I dont say that out loud because for example issues like this one makes it necessary to add it some default permissions. Yeah but wherever Android permits, we prefer run time notifications.

Sure, will keep in mind to explain permissions when anything is added.

**Comment by aschrijver** [comment]
If special permissions are required you might show an Onboarding dialog shown on first install that asks to enable them and otherwise tells you that you can do that in config too at a later time.

**Comment by adeekshith** [comment]
> If special permissions are required you might show an Onboarding dialog shown on first install that asks to enable them and otherwise tells you that you can do that in config too at a later time.

I'd like that wherever possible but Android requires some permissions to be specified in the APK itself. Not all permissions can be requested at run time.

Android classifies permissions into  "Dangerous" and "Normal" categories. Only dangerous permissions (like notification access) can be requested at run time. Permissions like "run at startup" and "internet" permissions are considered Normal permissions and these have to be included in the APK itself.
If normal permissions are required, the best we can do is to explain in the store listing why these are required.

**Comment by aschrijver** [comment]
Ah, okay. You might still show the Onboarding dialog that gives some very user-friendly explanation and builds that trust.
