### ISSUE TITLE
Layouts squishing and not scrollable for small screens and landscape mode

### ISSUE THREAD

**Issue by TheMindFlayer** [adeekshith/watomatic#147]
The app has some problem with the UI

- Phone: Huawei
- Model: LUA-U02
- Android Vers.: 5.1

I took some screenshots, when is landscape mode you can't scroll, the screen doesn't move (up or down) but the options work well.

If you need more info, say it, left some questions 

![Screenshot_2021-03-02-11-54-28](https://user-images.githubusercontent.com/17908649/109676920-88a3c880-7b4f-11eb-9fce-2c9e4dee148c.png)
![Screenshot_2021-03-02-11-54-35](https://user-images.githubusercontent.com/17908649/109676926-89d4f580-7b4f-11eb-8d1c-782508824b7c.png)
![Screenshot_2021-03-02-11-54-40](https://user-images.githubusercontent.com/17908649/109676929-8a6d8c00-7b4f-11eb-8985-dc9492d414fc.png)
![Screenshot_2021-03-02-11-54-48](https://user-images.githubusercontent.com/17908649/109676932-8b062280-7b4f-11eb-8550-2748687edae1.png)
![Screenshot_2021-03-02-11-54-56](https://user-images.githubusercontent.com/17908649/109676935-8b062280-7b4f-11eb-80d6-4aee4c3021af.png)

**Comment by adeekshith** [comment]
Oh this looks bad! Thanks for filing it in detail with screenshots Julio. Will see what is going wrong and work on this ASAP 👍

**Comment by adeekshith** [comment]
@TheMindFlayer 
Fixed this. It should now scroll well and also work in landscape mode too 😃🙌
Already in the process of pushing to Play store but that might take 2 to 3 days to roll out.

<img width="551" alt="Screen Shot 2021-03-02 at 11 06 15 PM" src="https://user-images.githubusercontent.com/2568945/109756660-f4b51980-7bad-11eb-8aa8-96cd1c5bf6d8.png">
