### ISSUE TITLE
Funding ideas RFC

### ISSUE THREAD

**Issue by aschrijver** [adeekshith/watomatic#160]
Github Sponsors seems to work well to get donations.

Other idea: You _might_ consider being a paid app in Google Play and free in F-Droid ([Fedilab](https://play.google.com/store/apps/details?id=app.fedilab.android) is doing this). But it will raise the barrier to use it, and at the same time promote F-Droid.

**Comment by adeekshith** [comment]
Any idea if we can include donate button in F-Droid version?

**Comment by aschrijver** [comment]
Not sure about that. I'd look at some other apps there. Maybe links are not allowed, but you might add them text-only.

**Comment by adeekshith** [comment]
> Github Sponsors seems to work well to get donations

Will give that a shot 😃
