### ISSUE TITLE
Not working on LG K3

### ISSUE THREAD

**Issue by voruti** [adeekshith/watomatic#180]
What details should I provide?

**Comment by voruti** [comment]
Works now with the latest version (v1.10).

**Comment by adeekshith** [comment]
Woohoo! Best bugs are the ones which fix themselves 😃

Glad the new fixes are working. Thought of writing a few troubleshooting instructions and post it here after work but glad you already figured.

Also working on having "Send Debug/Error Report" festure in the app so users can easily share it with the devs.

Thanks for coming back and updating. Really appreciate it @voruti !
Feel free to report if you face any other issues and please consider reviewing [**on Google Play**](https://play.google.com/store/apps/details?id=com.parishod.watomatic) 😊🙌
Thanks!
