### ISSUE TITLE
Reply only once per Contact per Day

### ISSUE THREAD

**Issue by OLLI-S** [adeekshith/watomatic#190]
A colleague wrote a message in WhatsApp and Watomatic replied.
Then my colleague replied with a smiley and received the Auto-Reply from Watomatic again.
He answered with "Ahhh" and received the Auto-Reply from Watomatic again.
Then he deleted me in WhatsApp, because these messages were annoying for him.

It would be better if I can select rhe frequency (how often Watomatic should reply).
When I select "Once per day" then each contact, that is writing me, gets this Auto-Reply from Watomatic only once per day.
This is contact specific (each contact gets the Auto-Reply from Watomatic only once per day).

There should be the following options:
* On each message
* Once per day
* Once per week
* Once per month
* Only once

The last option means, that the Auto-Reply from Watomatic is sent to this contact only once and then never again.

**Comment by adeekshith** [comment]
Hi @OLLI-S 
We already have a reply frequency feature that you can adjust from 1 day to 7 days. Did you try that?
<img width="382" alt="attrib-main" src="https://user-images.githubusercontent.com/2568945/111058426-3bc7c800-8454-11eb-8e9b-c7e41c6fc05a.png">

**Comment by OLLI-S** [comment]
This is so embarrassing for me, I just have overseen this feature.

**Comment by adeekshith** [comment]
@OLLI-S Oh no dont worry about that 😊.
I checked your other issues too and some of them are being worked on. Will keep you posted. Feel free to file more issues as you keep finding 🙂

**Comment by OLLI-S** [comment]
Please allow to extend the period to 30 days.
So I can select 30 days instead of 7 days.
