### ISSUE TITLE
Request Feature Contact exclusion

### ISSUE THREAD

**Issue by fikimaul** [adeekshith/watomatic#202]
Hi @adeekshith 

I alredy used this application for auto reply my friends chat. But sometime i need to exclude some my whatsapp contacts from the auto reply, because the chat from some contact is very importan and they dont have Signal or Telegram.

Thank You. 🍻

**Comment by adeekshith** [comment]
Hi @fikimaul 👋😃
Glad you are using it. Yeah, that's a good feature to have. Might take some time to implement but will working on this soon

**Comment by fikimaul** [comment]
Okay no problem. I will wait for that feature. 😄😄

**Comment by m-wagner98** [comment]
Yes great idea, waiting for that too

**Comment by OLLI-S** [comment]
I also support this suggestion
