### ISSUE TITLE
Indonesian Tranlate string.xml

### ISSUE THREAD

**Issue by What-Zit-Tooya** [adeekshith/watomatic#209]
I really like this app, so i translated it into Indonesian. Here the strings.xml : 
[strings(ID-id).zip](https://github.com/adeekshith/watomatic/files/6193765/strings.ID-id.zip)
Please include it in next release. 👍 

Best Regards

**Comment by adeekshith** [comment]
Hi @exodius48 👋😃
Thanks a lot! I guess you already found Crowdin page: https://crowdin.com/project/watomatic 
Crowdin also has option for translating Google Play listing so please check that out.

@fikimaul recently helped with Indonesian translations which I am reviewing. Feel free to discuss and improve on those too.
Thank you!

**Comment by exodius48** [comment]
> 
> 
> Hi @exodius48 👋😃
> Thanks a lot! I guess you already found Crowdin page: https://crowdin.com/project/watomatic
> Crowdin also has option for translating Google Play listing so please check that out.
> 
> @fikimaul recently helped with Indonesian translations which I am reviewing. Feel free to discuss and improve on those too.
> Thank you!

Before i sent xml i was applied crowdin, but not accepted, so i sent here. 

Im very glad, hope we can contribute in this project. :)
