### ISSUE TITLE
Show what's new in the release

### ISSUE THREAD

**Issue by spuday90** [adeekshith/watomatic#218]
Should fetch what's new data from github, if we have Telegram/Redit etc urls in it then user should be shown Whats new badge and on click redirect them to the corresponding urls based on which apps are installed in that device.

**Comment by adeekshith** [comment]
Github API to get latest release info: https://api.github.com/repos/adeekshith/watomatic/releases/latest

**Comment by adeekshith** [comment]
Important fields are:
- `id` this has release id. Unique id for each release (not version number).
- `prerelease`, `draft` should be false
- `body` We have add links to this. Was thinking something like this:
```
...
View release notes on:
Telegram: https://t.me/watomatic/10
Reddit: https://www.reddit.com/r/watomatic/comments/m7cq35/watomatic_113_released/
Twitter: https://twitter.com/watomatic/status/1372320884162232323
...
```

So we can look for `<app-name>: <url>` format in `body`

**Comment by adeekshith** [comment]
Alternative format which looks good in HTML but might be little difficult to parse?:
```
View release notes on [Telegram](https://t.me/watomatic/10), [Reddit](https://www.reddit.com/r/watomatic/comments/m7cq35/watomatic_113_released/), [Twitter](https://twitter.com/watomatic/status/1372320884162232323)
```

Format:
`View release notes on [App1](link1), [App2](link2)`

**Comment by adeekshith** [comment]
Added both the formats in the latest release notes.

We can also add `major-release: false` in one line somewhere in the body if we do not want to notify. But if that is not found, assume `true` by default

**Comment by adeekshith** [comment]
Looks like we can use `FLAG_ACTIVITY_REQUIRE_NON_BROWSER` intent flag to launch only if non-browser apps exist for that intent. Otherwise it throws exception and we can catch it to detect the app does not exist.

> `FLAG_ACTIVITY_REQUIRE_NON_BROWSER` This flag only launches the intent if it resolves to a result that is not a browser. If no such result exists, an ActivityNotFoundException will be thrown

Launching intents is fine but querying for intents now needs us to add permission to the manifest as per this article:

https://medium.com/androiddevelopers/working-with-package-visibility-dc252829de2d
