### ISSUE TITLE
Russian Translation strings.xml

### ISSUE THREAD

**Issue by OpenWarp** [adeekshith/watomatic#245]
While waiting for approval on Crowdin which may or may not happen I'd like to post translated strings.xml here to speed the things up. In fact, I have created a pull request for it already. Please let me know if you need translated main page https://adeekshith.github.io/watomatic/#/ and the privacy policy, in which case I would appreciate to have original .md files to work with. Thanks.
[strings_ru-rRU.zip](https://github.com/adeekshith/watomatic/files/6411584/strings_ru-rRU.zip)

**Comment by adeekshith** [comment]
Hi @OpenWarp 👋😃
Saw your translation PR yesterday and also accepted your Crowdin request a while ago. 
Out of town this weekend. Will get to your PR by tomorrow or will add those on Crowdin if you did not do already by tomorrow.

> Please let me know if you need translated main page https://adeekshith.github.io/watomatic/#/ and the privacy policy,

That would be great. Really appreciate it!! I'll figure out how to add these to Crowdin in the future but until then here are the md files:

.md files are at `docs/ghpages` branch:
https://github.com/adeekshith/watomatic/tree/docs/ghpages/docs 

Main page: [README.md](https://github.com/adeekshith/watomatic/blob/docs/ghpages/docs/README.md)
Privacy Policy: [privacy-policy.md](https://github.com/adeekshith/watomatic/blob/docs/ghpages/docs/privacy-policy.md)

Thanks a lot!! 😃

**Comment by OpenWarp** [comment]
Thank you so much @adeekshith and sorry for being impatient. Have a good one!

**Comment by mawoka-myblock** [comment]
@adeekshith should I create the website also for Russian?

**Comment by mawoka-myblock** [comment]
> Hi @OpenWarp 
> Saw your translation PR yesterday and also accepted your Crowdin request a while ago.
> Out of town this weekend. Will get to your PR by tomorrow or will add those on Crowdin if you did not do already by tomorrow.
> 
> > Please let me know if you need translated main page https://adeekshith.github.io/watomatic/#/ and the privacy policy,
> 
> That would be great. Really appreciate it!! I'll figure out how to add these to Crowdin in the future but until then here are the md files:
> 
> .md files are at `docs/ghpages` branch:
> https://github.com/adeekshith/watomatic/tree/docs/ghpages/docs
> 
> Main page: [README.md](https://github.com/adeekshith/watomatic/blob/docs/ghpages/docs/README.md)
> Privacy Policy: [privacy-policy.md](https://github.com/adeekshith/watomatic/blob/docs/ghpages/docs/privacy-policy.md)
> 
> Thanks a lot!!

There is also the _sidebar.md

**Comment by OpenWarp** [comment]
Done translating https://github.com/adeekshith/watomatic/tree/docs/ghpages/docs except for screenshot images and Github privacy policy. The latter is beyond the scope of this project. How do I go about translating images? Please advise.
[docs_ru-rRU.zip](https://github.com/adeekshith/watomatic/files/6414216/docs_ru-rRU.zip)

**Comment by mawoka-myblock** [comment]
Added it in #246

**Comment by adeekshith** [comment]
> How do I go about translating images? Please advise.

I could not find a quick way to do that via Crowdin. Will ask them and see if I missed anything.
I should also figure out how to integrate website translations with Crowdin. Will do that this week.

Thanks a lot @OpenWarp for the translations and @mawoka-myblock for adding it to the website 😃🙌

**Comment by mawoka-myblock** [comment]
Is live on the website! Good job, @OpenWarp

**Comment by OpenWarp** [comment]
@mawoka-myblock Thank you so much and may I suggest the hard to notice "Translations" link in the top right-hand corner to be replaced with the flag icon plus 3-letter language name. Then it's up to you to either put the flags in one line since there are few or to make it a drop down list. And would you be so kind to make sure Russian language reads "Russian" and not "Russia." Thanks.

**Comment by mawoka-myblock** [comment]
Will have a look at it. Maybe tomorrow!

**Comment by adeekshith** [comment]
@OpenWarp How is "Russian" written in Russian? Is this correct: "русский"

**Comment by mawoka-myblock** [comment]
> @mawoka-myblock Thank you so much and may I suggest the hard to notice "Translations" link in the top right-hand corner to be replaced with the flag icon plus a short language name (EN, DE, RU, and so on). Then it's up to you to either put the flags in one line since there are few or to make it a drop down list. And would you be so kind to make sure Russian language reads "Русский" and not "Russia." Thanks.

Which flag should I take for the translation-button?

**Comment by adeekshith** [comment]
> > @mawoka-myblock Thank you so much and may I suggest the hard to notice "Translations" link in the top right-hand corner to be replaced with the flag icon plus a short language name (EN, DE, RU, and so on). Then it's up to you to either put the flags in one line since there are few or to make it a drop down list. And would you be so kind to make sure Russian language reads "Русский" and not "Russia." Thanks.
> 
> @OpenWarp Which flag should I take for the translation-button?

I think just the localized language name and code should do for now.

Like this:

English (EN)
Deutsche (DE)
Русский (RU)

But if you like the idea of flags:
🇺🇸 English (EN)
🇩🇪 Deutsche (DE)
🇷🇺 Русский (RU)

I am slightly reluctant with idea of flags on the website as some languages are equally popular in more than one countries. Example, Tamil is equally spoken in India and Sri Lanka. So  we might run into conflicts but not totally against it. So if you think it is the right thing to do, go ahead :)

**Comment by OpenWarp** [comment]
Great job @mawoka-myblock ! Just updated the links in strings.xml via Crowdin, except for privacy policy link which is marked as non-translatable and is therefore hidden by Crowdin.

**Comment by adeekshith** [comment]
@OpenWarp Made the privacy policy url translatable 😊

**Comment by OpenWarp** [comment]
@adeekshith The `url_privacy_policy` string does not appear in Crowdin for some reason.

**Comment by adeekshith** [comment]
> @adeekshith The `url_privacy_policy` string does not appear in Crowdin for some reason.

Looks like Crowdin has some issue updating when a String is changed from non-translatable to translatable. Should probably change the string key. But redirecting automatically based on browser language is a better thing to do. Tracking it here: #281
