### ISSUE TITLE
Display couple screenshots on main README as well as on the website

### ISSUE THREAD

**Issue by adeekshith** [adeekshith/watomatic#28]
This would also cover almost all the information that we need for PlayStore

**Comment by aschrijver** [comment]
I would display at least one or two screenshots directly on the main README and then you can have a [More screenshots] to the other page.

**Comment by adeekshith** [comment]
Yeah thats a good suggestion @aschrijver . README page and webpage definitely needs some work. Will get to this tomorrow.

**Comment by adeekshith** [comment]
README page now has some screenshots 😃 https://github.com/adeekshith/watomatic 

Will consider using lower resolution images for faster loading but I think it is still better than no screenshots
