### ISSUE TITLE
Ask users to rate on Play store only for Google Play build

### ISSUE THREAD

**Issue by adeekshith** [adeekshith/watomatic#299]
As of now we have a single build flavor for Google Play as well as for F-Droid so we are also asking F-droid users also to rate on Google Play.
We should create separate build flavor for Google Play and include it only in that.

Not a high priority but it is the right thing to do.

**Comment by hegocre** [comment]
What if instead of creating two flavors, we simply check if app was installed from Google Play, with some function like [this](https://stackoverflow.com/questions/37539949/detect-if-an-app-is-installed-from-play-store)?

**Comment by adeekshith** [comment]
That's probably what we need. Didn't know about that. Will try doing that. Thanks @hegocre ☺️

**Comment by spuday90** [comment]
That's great idea. But it will be a temporary fix. If we have to do further customizations and say implement google rate api.

**Comment by adeekshith** [comment]
Yep, but as long as we are not including Play specific libraries, this looks like a good thing to do 😊
