### ISSUE TITLE
Language change not working when app downloaded from Play Store

### ISSUE THREAD

**Issue by hegocre** [adeekshith/watomatic#322]
I was just checking some things of some app of mine and i realized language was not changing sometimes (I use same method as used here). So I checked this app as well and it has the same problem.

After a long time trying to fix this issue, i found [this](https://github.com/YarikSOffice/lingver#app-bundles).

Basically, when the app is uploaded as aab to Google Play, only the locales selected by the user on the system are downloaded, so the app can't find any other locale and in consequence can't switch to it. Looks like the solution is downloading the resources on-demand using PlayCore API, or disable resource split at the cost of increasing the installed app size [as seen here](https://stackoverflow.com/a/52733674/5525931).

Not really urgent, but would be nice to fix this some time.

**Comment by adeekshith** [comment]
Thanks @hegocre 😃
Including Play core libraries might need us to create separate flavors as F-droid does not accept those libraries. I think disabling split by language might be fine. Guessing size increase should not be significant for our app.
