### ISSUE TITLE
Activity titles not being translated

### ISSUE THREAD

**Issue by adeekshith** [adeekshith/watomatic#323]
Might be we hardcoded it somewhere

![100px](https://user-images.githubusercontent.com/2568945/121794776-bed1f900-cbd0-11eb-87ca-c2dc2a3ef362.png)

**Comment by hegocre** [comment]
Looks like it's happening with all of the titles.

![AboutActivity](https://user-images.githubusercontent.com/15657088/121803374-84ed0b00-cc41-11eb-97b5-5e8c92d0ecfd.jpg)
