### ISSUE TITLE
Always-On notification reappears after a restart even though it is switched off.

### ISSUE THREAD

**Issue by kyoforkshomebrews** [adeekshith/watomatic#349]
I switched off the always on notification in watomatic but it still reappears after a restart. My workaround for now is to enable, then disable the option again.

**Comment by adeekshith** [comment]
Oh right! Noticed this recently. This will be fixed. Thanks for filing the issue 😊

**Comment by kyoforkshomebrews** [comment]
Thank *you* for the great app tho, hadn't had any other issues with it so far :)
