### ISSUE TITLE
The version number is blocked and cannot be seen fully

### ISSUE THREAD

**Issue by yuhuitech** [adeekshith/watomatic#357]
**Describe the bug**

Dear developer!
In the process of using, I found a bug in layout / display. As shown in the figure below, on the about page, **the version number not be seen fully**. This may be an adaptation problem. I suspect it is because **display and font size** are set to large **(mainly due to display size)**.
Because of some problems with my eyesight, I often use the largest font and display.
![103165857-dbaf8580-4857-11eb-9e22-120ae1901389](https://user-images.githubusercontent.com/25502419/128597553-7949a1a3-0b21-4ddf-9357-766b5c302518.png)

App version is 1.20, my mobile phone is Google Pixel 2, and the screen resolution setting is 1920* 1080. And **_my font size and display size are the largest ! ! !_** Also, my Android system version is 10.0.
The above is a description of the problem. The overall experience of the software is good. You can see that the design is very attentive. Thank you very much for the efforts of the developers all the time. I hope to receive a reply. Thank you so much!!

**Expected behavior**

I hope that I can see the version of this app fully. 

**Steps to reproduce the behavior:**

1.use the largest font and display in the display setting
2.click the three vertical dots on the top right of the main page and then click about
3.this error could be seen

**Screenshot**

(The blocked part is marked in red)

<img src="https://user-images.githubusercontent.com/25502419/130192993-fe1e6f24-00fb-4050-b1e6-1bfc81e4cba8.png" alt="copy" width="250"/>

**Environment**

1. Version of watomatic: 1.20
2. Device : Google Pixel 2,
3. OS version : Android 10.0

**Comment by spuday90** [comment]
Fixed in #358
