### ISSUE TITLE
Mastodon account for this project

### ISSUE THREAD

**Issue by Lukas2112** [adeekshith/watomatic#372]
Would a Mastodon account for this project be possible?

**Comment by adeekshith** [comment]
That would be great. Which instances would you recommend?

**Comment by Lukas2112** [comment]
Could I imagine social.tchncs.de or a regional instance?

**Comment by JakeHL** [comment]
I would always recommend fosstodon.org however I understand that some people dislike it as its an English only instance

**Comment by Lukas2112** [comment]
The great thing about Fediverse is that you can choose an instance and are not limited to one. :)

However, If the Watomatic project joins the Fediverse, I see as a win-win situation.

**Comment by Lukas2112** [comment]
Was there a request at fossrodon.org for a Mastodon account for the project @JakeHL ?

**Comment by adeekshith** [comment]
Yes! Created it this week. `@watomatic@fosstodon.org`  https://fosstodon.org/@watomatic 

And posted for the first time just now. Check it out 😃
