### ISSUE TITLE
iOS version 

### ISSUE THREAD

**Issue by DemonRem** [adeekshith/watomatic#376]
Hello @adeekshith 

can you add iOS support for iPhones?

**Comment by mawoka-myblock** [comment]
That's not possible, because Watomatic uses the Android notification framework, which, surprisingly, doesn't exist on iOS.

**Comment by vyeol** [comment]
Sorry to revive this thread, I just have a question for understanding:

[This thread](https://github.com/adeekshith/watomatic/pull/215) mentions that Watomatic relies on notification quick replies to function.

I just checked and confirmed that it is possible to use quick replies on notifications on iOS, i.e. long press a notification and there's a pop-up menu with various options, including quick replies for e.g. Signal.

Given this, would it still be impossible to develop an iOS version of Watomatic?
