### ISSUE TITLE
How did you create those nice screenshots?

### ISSUE THREAD

**Issue by rugk** [adeekshith/watomatic#381]
Wow how did you create those nice screenshots that do have these nice marketing quality with looking great in a slideshow…? :upside_down_face:

**Comment by rugk** [comment]
Though BTW I'd say the first two could be improved: IMHO the same screenshot should be shown on both because when you slide it, it otherwise makes no sense.

I know you want to show the dark mode but hmm… it's even another page, so at least the same page to avoid the visual "cut" in there. And maybe you can also place that dark mode demo in another screenshot…

**Comment by mawoka-myblock** [comment]
I've asked @adeekshith the same a year ago or so and I *+think**  it was the following website, but I am not 100% sure: https://studio.app-mockup.com/

**Comment by adeekshith** [comment]
Yep, thats the website I used to generate contiguous screenshots. And I used "Snapmod" app to generate device frames. I am surprised you remembered it and thanks for the reply @mawoka-myblock 😃

> I know you want to show the dark mode but hmm… it's even another page, so at least the same page to avoid the visual "cut" in there. And maybe you can also place that dark mode demo in another screenshot…

Noted. Thanks for the feedback @rugk 😊

**Comment by mawoka-myblock** [comment]
Yes, I've just searched a bit and one of this website was a bit familiar, so I suggested it!
