### ISSUE TITLE
App not working on Huawei P10 lite

### ISSUE THREAD

**Issue by Lir10** [adeekshith/watomatic#382]
is there any known devices that the app doesn't work on them?
Seems like on my Huawei P10 lite the app doesn't reply automatically at all
I'm testing it with WhatsApp

**Comment by adeekshith** [comment]
Try enabling Settings -> "Always-On notification" in Watomatic. That should prevent Android from killing the app in the background. But it is not working on a few devices even with that as some of them disabled those "WatchOS" APIs that Watomatic uses to function

Duplicate of #134
