### ISSUE TITLE
Reply frequency is not honored

### ISSUE THREAD

**Issue by JakeHL** [adeekshith/watomatic#386]
im on mobile so sorry for formatting and spelling. ill fix it up when I can.

I've got my reply frequency set to once every 2 days, however I've had the app auto reply two times in the space of a few minutes.

Not sure what other information I can provide to be helpful so heres anything I can think of:

Ive only seen it happen for a group chat (I've not been messaged frequently directly, lately to test)

I don't have any contact specific rules set.

I only use this app for whatsapp replies as I don't use messenger.

I have the persistent notification and have disabled battery optimizations.

I have the app set to notify me when it auto replies (and I had two in this instance)

im using version 1.20 from f droid.

I understand this feature is in beta so im not trying to be critical. I just want to help 👍

**Comment by adeekshith** [comment]
> Ive only seen it happen for a group chat

Hi @JakeHL. We fixed the group chat reply frequency issue sometime ago but it was not released. Planning to make a release soon that should fix it. The issue basically was when images are sent in group chat, WhatsApp was not marking that as an individual message sometimes so Watomatic was getting confused.

**Comment by JakeHL** [comment]
Ah, noted, thanks!
