### ISSUE TITLE
Always-On notification setting ignored after restarting the phone

### ISSUE THREAD

**Issue by te2dy** [adeekshith/watomatic#400]
Hello,

I have disabled the Always-On notification in the app's built-in notification settings, but when I restart my phone, the notification appears.

To make it disappear, I have to go to the app settings, then enable and disable the settings again.

I'm using version 1.20, and my phone is running Android 10 (/e/OS 1.2).

Otherwise, the app has been running smoothly for months! Thank you.

**Comment by adeekshith** [comment]
Fixed in the current version. Released to Izzyondroid. F-droid and play store release in the pipeline
