### ISSUE TITLE
[FEATURE REQ] Make attribution toggle more obvious.

### ISSUE THREAD

**Issue by ShockedCoder** [adeekshith/watomatic#403]
I've been searching for it for the past day, and I can't find the toggle in the app nor the code.

**Comment by ShockedCoder** [comment]
**WHERE THE HELL IS THE TOGGLE!?**

**Comment by adeekshith** [comment]
Current version of Google Play has it in the editor: https://t.me/WatomaticChat/227

Moved it to "Settings" in the future versions

**Comment by ShockedCoder** [comment]
I got it from F-Droid, though?

**Comment by ShockedCoder** [comment]
The editor
![Screenshot_20221007-214635_Watomatic.jpg](https://user-images.githubusercontent.com/40272709/194628456-82efca85-2217-4b56-b1a8-813913d5f9db.jpg)
