### ISSUE TITLE
Fatal Android 12: Exception: startForegroundService() not allowed due to mAllowStartForeground false

### ISSUE THREAD

**Issue by Lir10** [adeekshith/watomatic#406]
Now that Google Play is require apps to target api level 31 we can't use startForegroundService() from the [keepAlive service](https://github.com/adeekshith/watomatic/blob/main/app/src/main/java/com/parishod/watomatic/service/KeepAliveService.java#L98) as it will result in exception due to running a foreground service from the background.
See: https://stackoverflow.com/questions/70044393/fatal-android-12-exception-startforegroundservice-not-allowed-due-to-mallows

**Comment by adeekshith** [comment]
Thank you for reporting this @Lir10. Will plan to work on this once I get some free time. But in case you or other contributors can pick this up, that will be a lot of help. Thank you!

**Comment by adeekshith** [comment]
Planning to Migrate to API 33
- Official migration guide (currently only lists migrating to API 31): https://developer.android.com/google/play/requirements/target-sdk 
- Also read: https://developer.android.com/about/versions/12/migration
- Migrating to API 33 (third party blog): https://medium.com/tech-takeaways/migrating-my-app-to-android-13-f5ad0649d23d
