### ISSUE TITLE
Add option to allow users to set reply frequency in days

### ISSUE THREAD

**Issue by adeekshith** [adeekshith/watomatic#76]
Add a feature to allow users to set reply frequency. For example if the user sets frequency to 1 day, then it auto replies to same person only once every day.

We should perhaps remove the time picker and replace it with a number picker to pick number of days instead of min and hours.

**Comment by spuday90** [comment]
https://github.com/adeekshith/watomatic/pull/78#issuecomment-779621837

When we change the date manually, we are not receiving the remoteinput object from whatsapp notification hence it is failing to auto reply.
