### ISSUE TITLE
Add auto reply support for (leaving) Facebook Messenger

### ISSUE THREAD

**Issue by adeekshith** [adeekshith/watomatic#77]
![after-light-scaled](https://user-images.githubusercontent.com/2568945/108626401-8e91ff00-7415-11eb-85c9-65f8d7ff7ed6.png)

**Comment by TPS** [comment]
Wait, why would you promote leaving WhatsApp for _FaceBook_ Messenger?  Isn't FaceBook's changed policy re: WhatsApp the motivation to leave in the 1st place?

**Comment by adeekshith** [comment]
@TPS Haha I think I may need to reword the title if it is confusing. This issue is about adding ability to auto reply for Facebook messenger so people can leave that too just like we are currently doing for Whatsapp.

So they can set a message **"I am not using Facebook messenger anymore. Please use Signal or something"**

By "Support facebook messenger" I meant something like "add auto reply feature for Facebook so users can leave it"

Did that make sense?

**Comment by TPS** [comment]
Yep, & definitely reword the issue title.

**Comment by adeekshith** [comment]
> Yep, & definitely reword the issue title.

IMO, this title makes sense in context but feel free to suggest one

**Comment by TPS** [comment]
How about "Add support for _leaving_ Facebook Messenger"?

**Comment by adeekshith** [comment]
> How about "Add support for _leaving_ Facebook Messenger"?

Updated with slight changes.

**Comment by adeekshith** [comment]
Good news is, this feature is almost implemented 😃. There are just a few more rough edges that needs some work. Will plan to release this in a few days just in time when our [Australian friends are deleting Facebook](https://www.independent.co.uk/life-style/gadgets-and-tech/delete-facebook-australia-news-how-to-b1804005.html).
